---
- name: Create generic Ansible user
  hosts: my_servers
  become: yes
  tasks:
    - name: Create ansible user on RedHat and Rocky systems
      user:
        name: ansible
        password: "{{ 'ansible' | password_hash('sha512') }}"
        state: present
        shell: /bin/bash
        create_home: yes
      when: ansible_distribution in ['RedHat', 'Rocky']

    - name: Create ansible user on Ubuntu systems
      user:
        name: ansible
        password: "{{ 'ansible' | password_hash('sha512') }}"
        state: present
        shell: /bin/bash
        create_home: yes
      when: ansible_distribution == 'Ubuntu'

