---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install common packages
  ansible.builtin.package:
    name:
      - vim
      - curl
      - wget
    state: present

- name: Set timezone
  ansible.builtin.command:
    cmd: timedatectl set-timezone Etc/UTC
  when: ansible_os_family == 'Debian'
