---
- name: Copy SSH public key to servers
  hosts: all
  become: yes
  tasks:
    - name: Ensure .ssh directory exists
      file:
        path: /home/{{ ansible_user }}/.ssh
        state: directory
        mode: '0700'
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
      become_user: "{{ ansible_user }}"
      when: ansible_user != 'root'

    - name: Ensure .ssh directory exists for root
      file:
        path: /root/.ssh
        state: directory
        mode: '0700'
        owner: root
        group: root

    - name: Copy SSH public key to user .ssh directory
      copy:
        src: ~/.ssh/id_ed25519.pub
        dest: /home/{{ ansible_user }}/.ssh/authorized_keys
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0600'
      become_user: "{{ ansible_user }}"
      when: ansible_user != 'root'

    - name: Copy SSH public key to root .ssh directory
      copy:
        src: ~/.ssh/id_ed25519.pub
        dest: /root/.ssh/authorized_keys
        owner: root
        group: root
        mode: '0600'
