---
- name: Install Python3 on clients
  hosts: all
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Ensure Python 3 is installed on Ubuntu
      ansible.builtin.apt:
        name: python3
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: Ensure Python 3 pip is installed on Ubuntu
      ansible.builtin.apt:
        name: python3-pip
        state: present
      when: ansible_facts['os_family'] == "Debian"

