---
- name: Install and configure Node Exporter on clients
  hosts: all
  become: yes

  tasks:
    - name: Check if Node Exporter is installed
      stat:
        path: /usr/local/bin/node_exporter
      register: node_exporter_installed

    - name: Download Node Exporter
      shell: |
        wget https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
        tar xvfz node_exporter-1.3.1.linux-amd64.tar.gz
        mv node_exporter-1.3.1.linux-amd64/node_exporter /usr/local/bin/
      args:
        creates: /usr/local/bin/node_exporter
      when: node_exporter_installed.stat.exists == False

    - name: Set correct permissions for Node Exporter binary
      file:
        path: /usr/local/bin/node_exporter
        owner: root
        group: root
        mode: '0755'

    - name: Ensure proper SELinux context for Node Exporter binary
      command: chcon -t bin_t /usr/local/bin/node_exporter
      when: ansible_selinux.status == "enabled"

    - name: Create node_exporter user
      user:
        name: nodeusr
        shell: /sbin/nologin
      when: node_exporter_installed.stat.exists == False

    - name: Create systemd service for Node Exporter
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          User=nodeusr
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=default.target
      when: node_exporter_installed.stat.exists == False

    - name: Start and enable Node Exporter
      systemd:
        name: node_exporter
        state: started
        enabled: yes
      when: node_exporter_installed.stat.exists == False

    - name: Ensure Node Exporter service is restarted and running
      systemd:
        name: node_exporter
        state: restarted
      when: node_exporter_installed.stat.exists == True

    - name: Wait for Node Exporter service to stabilize
      pause:
        seconds: 15

    - name: Verify Node Exporter service is active and running
      systemd:
        name: node_exporter
        state: started
        enabled: yes
      register: result

    - name: Debug Node Exporter service status
      debug:
        var: result

    - name: Fail if Node Exporter is not running
      fail:
        msg: "Node Exporter service failed to start"
      when: result.status.ActiveState != "active"
