---
- name: Manage user accounts
  hosts: all
  become: yes
  tasks:
    - name: Manage user accounts for specific users
      user:
        name: "{{ target_user }}"
        state: "{{ user_state }}"
        shell: /bin/bash
        password: "{{ user_password | password_hash('sha512') }}"
      when: target_user is defined

