- name: Setup StrongSwan on VPN client
  hosts: all
  become: yes

  tasks:
    - name: Ensure EPEL repository is enabled
      ansible.builtin.yum:
        name: epel-release
        state: present

    - name: Ensure CodeReady Builder repository is enabled
      command: dnf config-manager --set-enabled crb

    - name: Install build dependencies
      ansible.builtin.yum:
        name:
          - gcc
          - gmp-devel
          - openssl-devel
          - readline-devel
          - pam-devel
          - bison
          - flex
          - make
          - wget
          - strongswan
          - strongswan-pkcs11
          - strongswan-tnccs
          - strongswan-tnc-imc
          - strongswan-tnc-imv
          - strongswan-libipsec
        state: present

    - name: Copy private key to client
      ansible.builtin.copy:
        src: /path/to/client-key.pem
        dest: /etc/strongswan/ipsec.d/private/client-key.pem
        owner: root
        group: root
        mode: '0600'

    - name: Ensure StrongSwan configuration directory exists
      ansible.builtin.file:
        path: /etc/strongswan
        state: directory

    - name: Configure StrongSwan
      ansible.builtin.template:
        src: templates/strongswan.conf.j2
        dest: /etc/strongswan/strongswan.conf
        owner: root
        group: root
        mode: '0644'

    - name: Ensure VICI socket directory exists
      ansible.builtin.file:
        path: /var/run
        state: directory

    - name: Create VICI socket file
      ansible.builtin.command:
        cmd: touch /var/run/charon.vici

    - name: Start and enable StrongSwan service
      ansible.builtin.systemd:
        name: strongswan
        enabled: yes
        state: started

    - name: Copy ipsec.secrets to client
      ansible.builtin.copy:
        src: templates/ipsec.secrets.j2
        dest: /etc/strongswan/ipsec.secrets
        owner: root
        group: root
        mode: '0600'

  handlers:
    - name: Restart StrongSwan
      ansible.builtin.systemd:
        name: strongswan
        state: restarted
